import {
  cp,
  mkdir,
  readFile,
  writeFile,
  access,
  readdir,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, resolve } from "node:path";
export async function createApp(destination: string, bundleId: string) {
  if (!/^[A-Za-z][A-Za-z0-9-]*(\.[A-Za-z][A-Za-z0-9-]*){2,}$/.test(bundleId))
    throw new Error(
      "Bundle identifier must be a reverse-DNS identifier with at least three components",
    );
  try {
    await access(destination);
    throw new Error("Destination exists; choose a new directory");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  }
  const here = fileURLToPath(new URL("../apple/", import.meta.url));
  const root = here.includes("/dist/") ? resolve(here, "../../apple") : here;
  await mkdir(destination, { recursive: true });
  for (const part of ["Shared", "App", "Messages", "project.yml"])
    await cp(join(root, part), join(destination, part), { recursive: true });
  let project = await readFile(join(destination, "project.yml"), "utf8");
  project = project
    .split("  MessagePilotVM:")[0]!
    .replaceAll("dev.messagepilot", bundleId);
  await writeFile(join(destination, "project.yml"), project);
  async function rewrite(dir: string) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) await rewrite(path);
      else if (/\.(swift|plist|entitlements)$/.test(entry.name))
        await writeFile(
          path,
          (await readFile(path, "utf8")).replaceAll(
            "dev.messagepilot",
            bundleId,
          ),
        );
    }
  }
  for (const part of ["Shared", "App", "Messages"])
    await rewrite(join(destination, part));
  await writeFile(
    join(destination, "README.md"),
    `# ${bundleId}\n\nGenerated by MessagePilot. Run xcodegen generate, select your Development Team, then build the host and Messages extension. Device signing and Apple enrollment remain local. No credentials are generated or embedded.\n`,
  );
}
