import {
  cp,
  mkdir,
  readFile,
  writeFile,
  access,
  readdir,
  rm,
} from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join, resolve } from "node:path";
export async function createApp(
  destination: string,
  bundleId: string,
  options: { primaryPort?: boolean; passkeyDomain?: string } = {},
) {
  if (
    options.passkeyDomain &&
    (!options.primaryPort ||
      !/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$/i.test(
        options.passkeyDomain,
      ))
  )
    throw new Error("A valid passkey domain requires primaryPort");
  if (!/^[A-Za-z][A-Za-z0-9-]*(\.[A-Za-z][A-Za-z0-9-]*){2,}$/.test(bundleId))
    throw new Error(
      "Bundle identifier must be a reverse-DNS identifier with at least three components",
    );
  try {
    await access(destination);
    throw new Error("Destination exists; choose a new directory");
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  }
  const here = fileURLToPath(new URL("../apple/", import.meta.url));
  const root = here.includes("/dist/") ? resolve(here, "../../apple") : here;
  await mkdir(destination, { recursive: true });
  for (const part of ["Shared", "App", "Messages", "Widgets", "project.yml"])
    await cp(join(root, part), join(destination, part), { recursive: true });
  let project = await readFile(join(destination, "project.yml"), "utf8");
  project = project
    .split("  MessagePilotVM:")[0]!
    .replaceAll("dev.messagepilot", bundleId);
  if (!options.primaryPort) {
    project = project
      .split("  MessagePilotWidgets:")[0]!
      .replace("      - target: MessagePilotWidgets\n", "")
      .replace(
        /^.*INFOPLIST_KEY_(NSLocationWhenInUseUsageDescription|NSCameraUsageDescription|NSSupportsLiveActivities|NSFaceIDUsageDescription).*\n/gm,
        "",
      )
      .replace(/^.*aps-environment:.*\n/gm, "");
    await rm(join(destination, "Widgets"), { recursive: true });
    await rm(join(destination, "Shared/SurfaceModels.swift"));
    for (const name of [
      "AppPort.swift",
      "AuthenticationPort.swift",
      "DeviceBridge.swift",
      "MessagePilotApp.swift",
    ])
      await rm(join(destination, "App", name));
    await cp(
      join(root, "Templates/MinimalApp.swift"),
      join(destination, "App/MessagePilotApp.swift"),
    );
    const entitlements = join(destination, "App/App.entitlements");
    const source = await readFile(entitlements, "utf8");
    await writeFile(
      entitlements,
      source.replace(
        /\s*<key>aps-environment<\/key>\s*<string>[^<]*<\/string>/,
        "",
      ),
    );
  }
  await writeFile(join(destination, "project.yml"), project);
  if (options.passkeyDomain) {
    project = project.replace(
      "        aps-environment: development",
      `        aps-environment: development\n        com.apple.developer.associated-domains: ['webcredentials:${options.passkeyDomain}']`,
    );
    await writeFile(join(destination, "project.yml"), project);
  }
  async function rewrite(dir: string) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) await rewrite(path);
      else if (/\.(swift|plist|entitlements)$/.test(entry.name))
        await writeFile(
          path,
          (await readFile(path, "utf8")).replaceAll(
            "dev.messagepilot",
            bundleId,
          ),
        );
    }
  }
  for (const part of [
    "Shared",
    "App",
    "Messages",
    ...(options.primaryPort ? ["Widgets"] : []),
  ])
    await rewrite(join(destination, part));
  await writeFile(
    join(destination, "README.md"),
    `# ${bundleId}\n\nGenerated by MessagePilot. Primary app port: ${options.primaryPort ? "enabled (widgets, Live Activities, App Intents, device bridge)" : "disabled (minimal containing app + Messages extension)"}. Run xcodegen generate, select your Development Team, then build the host and Messages extension. Device signing and Apple enrollment remain local. No credentials are generated or embedded.\n`,
  );
}
